/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  luotao
 * Created: 2017-3-7
 */

INSERT INTO TS_SEQUENCE(NAME,CURRENT_VALUE,INCREMENT) VALUES('SEQ_ATTR_ID',10000,1);
INSERT INTO TS_SEQUENCE(NAME,CURRENT_VALUE,INCREMENT) VALUES('SEQ_USER_ID',10000,1);
INSERT INTO TS_SEQUENCE(NAME,CURRENT_VALUE,INCREMENT) VALUES('SEQ_ORDER_ID',10000,1);
INSERT INTO TS_SEQUENCE(NAME,CURRENT_VALUE,INCREMENT) VALUES('SEQ_ORDER_DETAIL_ID',10000,1);
INSERT INTO TS_SEQUENCE(NAME,CURRENT_VALUE,INCREMENT) VALUES('SEQ_PRODUCT_ID',10000,1);
INSERT INTO TS_SEQUENCE(NAME,CURRENT_VALUE,INCREMENT) VALUES('SEQ_PRODUCT_INST_ID',10000,1);